# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Laundrify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Laundrify

  pod "AlamofireImage"
  pod "Parse"

  target 'LaundrifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LaundrifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
